package Cliente;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author E7240
 */
import javax.swing.*;
import Clases.Operaciones;
import Clases.Bodega;
import Clases.Facturacion;
import Clases.Farmaco;
import java.util.ArrayList;
public class frmFactura extends javax.swing.JFrame {

    /**
     * Creates new form frmFactura
     */
    Operaciones op = new Operaciones();
    int index= -1;
    public frmFactura() {
        initComponents();
        txtNumFact.setEnabled(false);
        txtCedCli.setEnabled(false);
        txtFecha.setEnabled(false);
        txtCodEmp.setEnabled(false);
        txtCant.setEnabled(false);
        txtCodFar.setEnabled(false);
        
        
        btnNuevo.setEnabled(true);
        btnConsultar.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnGenerar.setEnabled(false);
        btnSalir.setEnabled(true);
        btnOK.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNumFact = new javax.swing.JTextField();
        txtCedCli = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtCodEmp = new javax.swing.JTextField();
        txtCant = new javax.swing.JTextField();
        txtCodFar = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles de la factura"));

        jLabel1.setText("Numero de Factura:");

        jLabel2.setText("Cedula Cliente:");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Codigo de Empleado:");

        jLabel5.setText("Cantidad:");

        jLabel6.setText("Codigo Farmaco:");

        jLabel7.setText("Precio:");

        jLabel8.setText("Subtotal:");

        txtNumFact.setName("txtNumFact"); // NOI18N

        txtCedCli.setName("txtCedCli"); // NOI18N

        txtFecha.setName("txtFecha"); // NOI18N

        txtCodEmp.setName("txtCodEmp"); // NOI18N

        txtCant.setName("txtCant"); // NOI18N

        txtCodFar.setName("txtCodFar"); // NOI18N

        lblPrecio.setName("lblPrecio"); // NOI18N

        lblSub.setName("lblSub"); // NOI18N

        btnOK.setText("OK");
        btnOK.setName("btnOK"); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodFar, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(txtCant)
                    .addComponent(txtCodEmp)
                    .addComponent(txtFecha)
                    .addComponent(txtCedCli)
                    .addComponent(txtNumFact)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOK)
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNumFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCedCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCodFar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblSub, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnOK)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-recibo-30.png"))); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.setName("btnGenerar"); // NOI18N
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, -1));

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/magnifier.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setName("btnConsultar"); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/drive_user.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setName("btnNuevo"); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pencil.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setName("btnModificar"); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setName("btnEliminar"); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/door_in.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setName("btnSalir"); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-recibo-30.png"))); // NOI18N
        jLabel14.setText("Factura");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Monto a pagar"));

        jLabel10.setText("Subtotal:");

        jLabel11.setText("Impuesto:");

        jLabel12.setText("Total:");

        lblSubTotal.setName("lblSubTotal"); // NOI18N

        lblIVA.setName("lblIVA"); // NOI18N

        lblTotal.setName("lblTotal"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(lblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(lblIVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 170, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        boolean v= false;
        boolean valid=false;
        int num= Integer.parseInt(txtCant.getText());
        for(int w=0;w<op.array_Bodega.size();w++){
            Bodega b = (Bodega)op.array_Bodega.get(w);
            int digit= op.array_Bodega.get(w).getCantidad();
            if(num>digit){
                valid=true;
            }
            if(valid==true){
                JOptionPane.showMessageDialog(null, "La existencia del farmaco en bodega es menor que la solicitada, realice un pedido.");
                txtNumFact.setEnabled(false);
        txtFecha.setEnabled(false);
        txtCedCli.setEnabled(false);
        txtCodEmp.setEnabled(false);
        txtCant.setEnabled(false);
        txtCodFar.setEnabled(false);
        
        txtNumFact.setText("");
        txtFecha.setText("");
        txtCedCli.setText("");
        txtCodEmp.setText("");
        txtCant.setText("");
        txtCodFar.setText("");
        lblPrecio.setText("");
        lblSub.setText("");
        lblIVA.setText("");
        lblSubTotal.setText("");
        lblTotal.setText("");
        
        
        
        btnNuevo.setEnabled(true);
        btnConsultar.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnGenerar.setEnabled(false);
        btnSalir.setEnabled(true);
        btnOK.setEnabled(false);
        
                
            }
            else{
                if(txtNumFact.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe digitar un numero de factura");
        }
        else{
            int numFac= Integer.parseInt(txtNumFact.getText());
            
            for(int i=0;i<op.array_Factura.size();i++){
                Facturacion fac = (Facturacion)op.array_Factura.get(i);
                
                if(op.array_Factura.get(i).getNumero()==numFac){
                    v=true;
                    
                }
            }
            if(v==true){
                JOptionPane.showMessageDialog(null, "El numero de factura ya existe, digite otro");
            }
            else{
                
                if(txtCodFar.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Debe digitar un codigo de farmaco");
                }else{
                    boolean err=false;
                    
                    int codFar= Integer.parseInt(txtCodFar.getText());
                    
                    for(int i=0;i<op.array_Farmaco.size();i++){
                        Farmaco far = (Farmaco)op.array_Farmaco.get(i);
                        
                        if(op.array_Farmaco.get(i).getcodFarmaco()==codFar){
                            
                            
                            int cant= Integer.parseInt(txtCant.getText());
                            index=op.encuentraBodega(codFar);
                            if(index!=-1){
                            for(int j=0;j<op.array_Bodega.size();j++){
                                Bodega bode = (Bodega)op.array_Bodega.get(i);
                                if(op.array_Bodega.get(i).getCodFarmaco()==codFar){
                                    err=true;
                                }
                                if(err==true){
                                    for(int k=0;k<op.array_Bodega.size();k++){
                                      Bodega bodega = (Bodega)op.array_Bodega.get(i);
                                      if(op.array_Bodega.get(i).getCantidad()>=cant){
                                          int aux = op.array_Bodega.get(i).getCantidad();
                                          int cantidad= aux-cant;
                                          int codFarmaco= op.array_Bodega.get(i).getCodFarmaco();
                                          String sucursal= op.array_Bodega.get(i).getSucursal();
                                          String codEstado= op.array_Bodega.get(i).getCodEstado();
                                          op.modificar(index, codFarmaco, codEstado, cantidad, sucursal);
                                      
                                      }
                                      
                                      
                                           }
                                    
                                }
                                
                                   
                                }
                            }
                            lblPrecio.setText(String.valueOf(far.getPrecio()));
                            int precio= Integer.parseInt(lblPrecio.getText());
                            
                            int subTotal= cant*precio;
                            lblSub.setText(String.valueOf(subTotal));
                            lblSubTotal.setText(String.valueOf(subTotal));
                            double impuesto= 0.13;
                            lblIVA.setText(String.valueOf(impuesto));
                            double totalFinal= (subTotal*impuesto)+subTotal;
                            lblTotal.setText(String.valueOf(totalFinal));
                        }
                    }
                
                int numero= Integer.parseInt(txtNumFact.getText());
                int fecha= Integer.parseInt(txtFecha.getText());
                int cedCliente= Integer.parseInt(txtCedCli.getText());
                int codEmpleado= Integer.parseInt(txtCodEmp.getText());
                int cantidad= Integer.parseInt(txtCant.getText());
                int codFarmaco= Integer.parseInt(txtCodFar.getText());
                int precio= Integer.parseInt(lblPrecio.getText());
                int subTotal= Integer.parseInt(lblSub.getText());
                double impuesto= Double.parseDouble(lblIVA.getText());
                double totalFinal= Double.parseDouble(lblTotal.getText());
                op.agregar(numero, fecha, cedCliente, codEmpleado, cantidad, codFarmaco, precio, subTotal, impuesto, totalFinal);
                }
                        
            }
        }
            }
        }
        
        
        
        
        txtNumFact.setEnabled(false);
        txtFecha.setEnabled(false);
        txtCedCli.setEnabled(false);
        txtCodEmp.setEnabled(false);
        txtCant.setEnabled(false);
        txtCodFar.setEnabled(false);
        
//        txtNumFact.setText("");
//        txtFecha.setText("");
//        txtCedCli.setText("");
//        txtCodEmp.setText("");
//        txtCant.setText("");
//        txtCodFar.setText("");
//        lblPrecio.setText("");
//        lblSub.setText("");
//        lblIVA.setText("");
//        lblSubTotal.setText("");
//        lblTotal.setText("");
        
        
        
        btnNuevo.setEnabled(true);
        btnConsultar.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnGenerar.setEnabled(false);
        btnSalir.setEnabled(true);
        btnOK.setEnabled(false);
        
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        boolean v= false;
        
        if(txtNumFact.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite un numero de factura");
        }
        else{
            int cod= Integer.parseInt(txtNumFact.getText());
            
            for(int i=0;i<op.array_Factura.size();i++){
                Facturacion fact = (Facturacion)op.array_Factura.get(i);
                if(op.array_Factura.get(i).getNumero()==cod){
                    v=true;
                }
            }
            if(v==true){
                for(int i=0;i<op.array_Factura.size();i++){
                    Facturacion fact = (Facturacion)op.array_Factura.get(i);
                    if(op.array_Factura.get(i).getNumero()==cod){
                        txtCedCli.setText(String.valueOf(fact.getCedCliente()));
                        txtFecha.setText(String.valueOf(fact.getFecha()));
                        txtCodEmp.setText(String.valueOf(fact.getCodEmpleado()));
                        txtCant.setText(String.valueOf(fact.getCantidad()));
                        txtCodFar.setText(String.valueOf(fact.getCodFarmaco()));
                        lblPrecio.setText(String.valueOf(fact.getPrecio()));
                        lblSub.setText(String.valueOf(fact.getSubtotal()));
                        lblIVA.setText(String.valueOf(fact.getImpuesto()));
                        lblTotal.setText(String.valueOf(fact.getTotalFinal()));
                        lblSubTotal.setText(String.valueOf(fact.getSubtotal()));
                    }
                }
            }
        }
        txtNumFact.setEnabled(true);
        txtCedCli.setEnabled(true);
        txtFecha.setEnabled(true);
        txtCodEmp.setEnabled(true);
        txtCant.setEnabled(true);
        txtCodFar.setEnabled(true);
        
        
        
        btnNuevo.setEnabled(true);
        btnConsultar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnGenerar.setEnabled(false);
        btnSalir.setEnabled(true);
        btnOK.setEnabled(false);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        txtNumFact.setText("");
        txtCedCli.setText("");
        txtFecha.setText("");
        txtCodEmp.setText("");
        txtCant.setText("");
        txtCodFar.setText("");
        lblPrecio.setText("");
        lblSub.setText("");
        lblIVA.setText("");
        lblTotal.setText("");
        lblSubTotal.setText("");
        
        
        txtNumFact.setEnabled(true);
        txtCedCli.setEnabled(false);
        txtFecha.setEnabled(false);
        txtCodEmp.setEnabled(false);
        txtCant.setEnabled(false);
        txtCodFar.setEnabled(false);
        
        
        
        btnNuevo.setEnabled(false);
        btnConsultar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnGenerar.setEnabled(false);
        btnSalir.setEnabled(true);
        btnOK.setEnabled(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        txtNumFact.setText("");
        txtCedCli.setText("");
        txtFecha.setText("");
        txtCodEmp.setText("");
        txtCant.setText("");
        txtCodFar.setText("");
        lblPrecio.setText("");
        lblSub.setText("");
        lblIVA.setText("");
        lblTotal.setText("");
        lblSubTotal.setText("");
        
        
        txtNumFact.setEnabled(true);
        txtCedCli.setEnabled(true);
        txtFecha.setEnabled(true);
        txtCodEmp.setEnabled(true);
        txtCant.setEnabled(true);
        txtCodFar.setEnabled(true);
        
        
        
        btnNuevo.setEnabled(false);
        btnConsultar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnGenerar.setEnabled(true);
        btnSalir.setEnabled(true);
        btnOK.setEnabled(false);
    
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       boolean v= false;
        boolean valid=false;
        if(txtNumFact.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe digitar un numero de factura");
        }
        else{
            int numFac= Integer.parseInt(txtNumFact.getText());
            
            for(int i=0;i<op.array_Factura.size();i++){
                Facturacion fac = (Facturacion)op.array_Factura.get(i);
                
                if(op.array_Factura.get(i).getNumero()==numFac){
                    v=true;
                    
                }
            }
            if(v==true){
                
        int num= Integer.parseInt(txtCant.getText());
        for(int w=0;w<op.array_Bodega.size();w++){
            Bodega b = (Bodega)op.array_Bodega.get(w);
            int digit= op.array_Bodega.get(w).getCantidad();
            if(num>digit){
                valid=true;
            }
            if(valid==true){
                JOptionPane.showMessageDialog(null, "La existencia del farmaco en bodega es menor que la solicitada, realice un pedido.");
                txtNumFact.setEnabled(false);
        txtFecha.setEnabled(false);
        txtCedCli.setEnabled(false);
        txtCodEmp.setEnabled(false);
        txtCant.setEnabled(false);
        txtCodFar.setEnabled(false);
        
        txtNumFact.setText("");
        txtFecha.setText("");
        txtCedCli.setText("");
        txtCodEmp.setText("");
        txtCant.setText("");
        txtCodFar.setText("");
        lblPrecio.setText("");
        lblSub.setText("");
        lblIVA.setText("");
        lblSubTotal.setText("");
        lblTotal.setText("");
        
        
        
        btnNuevo.setEnabled(true);
        btnConsultar.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnGenerar.setEnabled(false);
        btnSalir.setEnabled(true);
        btnOK.setEnabled(false);
        
                
            }
            else{
                
                if(txtCodFar.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Debe digitar un codigo de farmaco");
                }else{
                    boolean err=false;
                    
                    int codFar= Integer.parseInt(txtCodFar.getText());
                    
                    for(int i=0;i<op.array_Farmaco.size();i++){
                        Farmaco far = (Farmaco)op.array_Farmaco.get(i);
                        
                        if(op.array_Farmaco.get(i).getcodFarmaco()==codFar){
                            
                            
                            int cant= Integer.parseInt(txtCant.getText());
                            index=op.encuentraBodega(codFar);
                            if(index!=-1){
                            for(int j=0;j<op.array_Bodega.size();j++){
                                Bodega bode = (Bodega)op.array_Bodega.get(i);
                                if(op.array_Bodega.get(i).getCodFarmaco()==codFar){
                                    err=true;
                                }
                                if(err==true){
                                    for(int k=0;k<op.array_Bodega.size();k++){
                                      Bodega bodega = (Bodega)op.array_Bodega.get(i);
                                      if(op.array_Bodega.get(i).getCantidad()>=cant){
                                          int aux = op.array_Bodega.get(i).getCantidad();
                                          int cantidad= aux-cant;
                                          int codFarmaco= op.array_Bodega.get(i).getCodFarmaco();
                                          String sucursal= op.array_Bodega.get(i).getSucursal();
                                          String codEstado= op.array_Bodega.get(i).getCodEstado();
                                          op.modificar(index, codFarmaco, codEstado, cantidad, sucursal);
                                      
                                      }
                                      
                                      
                                           }
                                    
                                }
                                
                                   
                                }
                            }
                            lblPrecio.setText(String.valueOf(far.getPrecio()));
                            int precio= Integer.parseInt(lblPrecio.getText());
                            
                            int subTotal= cant*precio;
                            lblSub.setText(String.valueOf(subTotal));
                            lblSubTotal.setText(String.valueOf(subTotal));
                            double impuesto= 0.13;
                            lblIVA.setText(String.valueOf(impuesto));
                            double totalFinal= (subTotal*impuesto)+subTotal;
                            lblTotal.setText(String.valueOf(totalFinal));
                        }
                    }
                
                int numero= Integer.parseInt(txtNumFact.getText());
                int fecha= Integer.parseInt(txtFecha.getText());
                int cedCliente= Integer.parseInt(txtCedCli.getText());
                int codEmpleado= Integer.parseInt(txtCodEmp.getText());
                int cantidad= Integer.parseInt(txtCant.getText());
                int codFarmaco= Integer.parseInt(txtCodFar.getText());
                int precio= Integer.parseInt(lblPrecio.getText());
                int subTotal= Integer.parseInt(lblSub.getText());
                double impuesto= Double.parseDouble(lblIVA.getText());
                double totalFinal= Double.parseDouble(lblTotal.getText());
                op.modificar(index, numero, fecha, cedCliente, codEmpleado, cantidad, codFarmaco, precio, subTotal, impuesto, totalFinal);
                }
            }
        }
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
                boolean v = false;
        int num= Integer.parseInt(txtNumFact.getText());
        if(txtNumFact.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite un numero de factura");
        }
        else{
            for(int i=0; i<op.array_Factura.size(); i++){
                
                if(op.array_Factura.get(i).getNumero()== num){
                    v= true;
                }
                
            }
        
        
        if(v==true){
            for(int i=0;i<op.array_Factura.size();i++){
                if(op.array_Factura.get(i).getCedCliente()==num){
                    op.array_Factura.remove(i);
                    v=true;
                    JOptionPane.showMessageDialog(null, "Se eliminaron correctamente los datos");
                }
                
        
            }
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No se encontro el numero de factura");
        }
        }
        txtNumFact.setText("");
        txtCedCli.setText("");
        txtFecha.setText("");
        txtCodEmp.setText("");
        txtCant.setText("");
        txtCodFar.setText("");
        
        
        txtNumFact.setEnabled(false);
        txtCedCli.setEnabled(false);
        txtFecha.setEnabled(false);
        txtCodEmp.setEnabled(false);
        txtCant.setEnabled(false);
        txtCodFar.setEnabled(false);
        
        
        btnOK.setEnabled(false);
        btnConsultar.setEnabled(true);
        btnGenerar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnSalir.setEnabled(true);
        

    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCedCli;
    private javax.swing.JTextField txtCodEmp;
    private javax.swing.JTextField txtCodFar;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNumFact;
    // End of variables declaration//GEN-END:variables
}
