/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

/**
 *
 * @author E7240
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuEmpleado = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuFarmaco = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuBodega = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuPedido = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuDepartamento = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuCategoria = new javax.swing.JMenuItem();
        menuEstado = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuReporte = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuGenerar = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/treatment.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/application_form.png"))); // NOI18N
        menuArchivo.setText("Archivo");
        menuArchivo.setName("menuArchivo"); // NOI18N

        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/drive_user.png"))); // NOI18N
        menuCliente.setText("Cliente");
        menuCliente.setName("menuCliente"); // NOI18N
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        menuArchivo.add(menuCliente);
        menuArchivo.add(jSeparator1);

        menuEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-conocimiento-del-cliente-30.png"))); // NOI18N
        menuEmpleado.setText("Empleado");
        menuEmpleado.setName("menuEmpleado"); // NOI18N
        menuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadoActionPerformed(evt);
            }
        });
        menuArchivo.add(menuEmpleado);
        menuArchivo.add(jSeparator2);

        menuFarmaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-jeringa-30.png"))); // NOI18N
        menuFarmaco.setText("Farmaco");
        menuFarmaco.setName("menuFarmaco"); // NOI18N
        menuFarmaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFarmacoActionPerformed(evt);
            }
        });
        menuArchivo.add(menuFarmaco);
        menuArchivo.add(jSeparator3);

        menuBodega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-almacén-30.png"))); // NOI18N
        menuBodega.setText("Bodega");
        menuBodega.setName("menuBodega"); // NOI18N
        menuBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBodegaActionPerformed(evt);
            }
        });
        menuArchivo.add(menuBodega);
        menuArchivo.add(jSeparator4);

        menuPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-plan-de-tratamiento-30.png"))); // NOI18N
        menuPedido.setText("Pedido");
        menuPedido.setName("menuPedido"); // NOI18N
        menuPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidoActionPerformed(evt);
            }
        });
        menuArchivo.add(menuPedido);
        menuArchivo.add(jSeparator5);

        menuDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-departamento-30.png"))); // NOI18N
        menuDepartamento.setText("Departamento");
        menuDepartamento.setName("menuDepartamento"); // NOI18N
        menuDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDepartamentoActionPerformed(evt);
            }
        });
        menuArchivo.add(menuDepartamento);
        menuArchivo.add(jSeparator6);

        menuCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-gráfico-de-barras-30.png"))); // NOI18N
        menuCategoria.setText("Categoria");
        menuCategoria.setName("menuCategoria"); // NOI18N
        menuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaActionPerformed(evt);
            }
        });
        menuArchivo.add(menuCategoria);

        menuEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-estado-desconocido-26.png"))); // NOI18N
        menuEstado.setText("Estado");
        menuEstado.setName("menuEstado"); // NOI18N
        menuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstadoActionPerformed(evt);
            }
        });
        menuArchivo.add(menuEstado);

        jMenuBar2.add(menuArchivo);

        menuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/book.png"))); // NOI18N
        menuReportes.setText("Reportes");
        menuReportes.setName("menuReportes"); // NOI18N

        menuReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/book.png"))); // NOI18N
        menuReporte.setText("Reportes");
        menuReporte.setName("menuReporte"); // NOI18N
        menuReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReporteActionPerformed(evt);
            }
        });
        menuReportes.add(menuReporte);

        jMenuBar2.add(menuReportes);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-factura-16.png"))); // NOI18N
        jMenu1.setText("Facturar");

        menuGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-factura-16.png"))); // NOI18N
        menuGenerar.setText("Generar");
        menuGenerar.setName("menuGenerar"); // NOI18N
        menuGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGenerarActionPerformed(evt);
            }
        });
        jMenu1.add(menuGenerar);

        jMenuBar2.add(jMenu1);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/door_in.png"))); // NOI18N
        jMenu6.setText("Salir");
        jMenu6.setName("menuSalir"); // NOI18N

        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/door_in.png"))); // NOI18N
        menuSalir.setText("Salir Sistema");
        menuSalir.setName("menuSalir"); // NOI18N
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu6.add(menuSalir);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadoActionPerformed
        frmEmpleado emp = new frmEmpleado();
        emp.setVisible(true);
    }//GEN-LAST:event_menuEmpleadoActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        frmCliente cli = new frmCliente();
        cli.setVisible(true);
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuFarmacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFarmacoActionPerformed
        frmFarmaco far = new frmFarmaco();
        far.setVisible(true);
    }//GEN-LAST:event_menuFarmacoActionPerformed

    private void menuBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBodegaActionPerformed
        frmBodega bode = new frmBodega();
        bode.setVisible(true);
    }//GEN-LAST:event_menuBodegaActionPerformed

    private void menuPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidoActionPerformed
         frmPedido pedi = new frmPedido();
         pedi.setVisible(true);
    }//GEN-LAST:event_menuPedidoActionPerformed

    private void menuDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDepartamentoActionPerformed
        frmDepartamento dep = new frmDepartamento();
        dep.setVisible(true);
    }//GEN-LAST:event_menuDepartamentoActionPerformed

    private void menuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaActionPerformed
        frmCategoria cat = new frmCategoria();
        cat.setVisible(true);
    }//GEN-LAST:event_menuCategoriaActionPerformed

    private void menuGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGenerarActionPerformed
        frmFactura fact = new frmFactura();
        fact.setVisible(true);
    }//GEN-LAST:event_menuGenerarActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstadoActionPerformed
        frmEstado est = new frmEstado();
        est.setVisible(true);
    }//GEN-LAST:event_menuEstadoActionPerformed

    private void menuReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReporteActionPerformed
        frmReportes rep = new frmReportes();
        rep.setVisible(true);
    }//GEN-LAST:event_menuReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuBodega;
    private javax.swing.JMenuItem menuCategoria;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuDepartamento;
    private javax.swing.JMenuItem menuEmpleado;
    private javax.swing.JMenuItem menuEstado;
    private javax.swing.JMenuItem menuFarmaco;
    private javax.swing.JMenuItem menuGenerar;
    private javax.swing.JMenuItem menuPedido;
    private javax.swing.JMenuItem menuReporte;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
}
