package Cliente;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author E7240
 */
import java.util.ArrayList;
import Clases.Pedido;
import Clases.Operaciones;
import Clases.Bodega;
       
public class frmPedido extends javax.swing.JFrame {

    /**
     * Creates new form frmPedido
     */
    Operaciones op = new Operaciones();
    int index=-1;
    public frmPedido() {
        initComponents();
        
        txtCodigo.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtSucursal.setEnabled(false);
        
        
        btnOK.setEnabled(false);
        btnConsultar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnSalir.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtSucursal = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));

        jLabel1.setText("Codigo Farmaco:");

        jLabel2.setText("Cantidad:");

        jLabel3.setText("Sucursal:");

        txtCodigo.setName("txtCodigo"); // NOI18N
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        txtCantidad.setName("txtCantidad"); // NOI18N
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        txtSucursal.setName("txtSucursal"); // NOI18N

        btnOK.setText("OK");
        btnOK.setName("btnOK"); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad)
                            .addComponent(txtCodigo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 41, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnOK)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, 290));

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/magnifier.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setName("btnConsultar"); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/drive_user.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setName("btnNuevo"); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disk.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencil.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setName("btnModificar"); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setName("btnEliminar"); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/door_in.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setName("btnSalir"); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-plan-de-tratamiento-30.png"))); // NOI18N
        jLabel4.setText("Pedido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char c= evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "No se puede digitar letras");
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c= evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "No se puede digitar letras");
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        txtCodigo.setText("");
        txtCantidad.setText("");
        txtSucursal.setText("");
        
        txtCodigo.setEnabled(true);
        txtCantidad.setEnabled(false);
        txtSucursal.setEnabled(false);
        
        
        btnOK.setEnabled(true);
        btnConsultar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnSalir.setEnabled(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        txtCodigo.setEnabled(true);
        txtCantidad.setEnabled(true);
        txtSucursal.setEnabled(true);
        
        
        btnOK.setEnabled(false);
        btnConsultar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnSalir.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        boolean v= false;
        
        if(txtCodigo.getText().isEmpty()||txtCantidad.getText().isEmpty()||txtSucursal.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "No se pueden dejar espacios en blanco");

        }
        else{
            int cod= Integer.parseInt(txtCodigo.getText());
            int aux= Integer.parseInt(txtCantidad.getText());
            for(int i=0;i<op.array_Pedido.size();i++){
                Pedido pe = (Pedido)op.array_Pedido.get(i);
                if(op.array_Pedido.get(i).getCodFarmaco()==cod){
                 v=true;   
                }
            }
            if(v==true){
                JOptionPane.showMessageDialog(null, "El pedido ya se realizo, digite otro farmaco");
            }
            else{
                int codFarmaco= Integer.parseInt(txtCodigo.getText());
                int cantidad= Integer.parseInt(txtCantidad.getText());
                String sucursal= txtSucursal.getText();
                
                op.agregar(codFarmaco, sucursal, cantidad);
            }
            boolean valid=false;
            index=op.encuentraBodega(cod);
            if(index!=-1){
            for(int j=0;j<op.array_Bodega.size();j++){
                Bodega bod = (Bodega)op.array_Bodega.get(j);
                if(op.array_Bodega.get(j).getCodFarmaco()==cod){
                    int adicion= op.array_Bodega.get(j).getCantidad();
                    int cantidad= adicion+aux;
                    int codFarmaco= op.array_Bodega.get(j).getCodFarmaco();
                    String sucursal= op.array_Bodega.get(j).getSucursal();
                    String codEstado= op.array_Bodega.get(j).getCodEstado();
                    op.modificar(index, codFarmaco, codEstado, cantidad, sucursal);
                }
            }
            }
        }
        txtCodigo.setText("");
        txtCantidad.setText("");
        txtSucursal.setText("");
        
        txtCodigo.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtSucursal.setEnabled(false);
        
        
        btnOK.setEnabled(false);
        btnConsultar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnSalir.setEnabled(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        
        boolean v= false;
        
        if(txtCodigo.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Se debe digitar un codigo de farmaco");

        }
        else{
            int cod= Integer.parseInt(txtCodigo.getText());
            
            for(int i=0;i<op.array_Pedido.size();i++){
                Pedido pe = (Pedido)op.array_Pedido.get(i);
                if(op.array_Pedido.get(i).getCodFarmaco()==cod){
                 v=true;   
                }
            }
            if(v==true){
             for(int i=0;i<op.array_Pedido.size();i++){
                 Pedido pe = (Pedido)op.array_Pedido.get(i);
                 
                 if(op.array_Pedido.get(i).getCodFarmaco()==cod){
                     txtCantidad.setText(String.valueOf(pe.getCantidad()));
                     txtSucursal.setText(pe.getSucursal());
                 }
             }
            }
            else{
                JOptionPane.showMessageDialog(null, "No se ha realizado un pedido");
                txtCodigo.setText("");
                txtCodigo.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtSucursal.setEnabled(false);
        
            }
        }
        
        
        txtCodigo.setEnabled(true);
        txtCantidad.setEnabled(true);
        txtSucursal.setEnabled(true);
        
        
        btnOK.setEnabled(false);
        btnConsultar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnSalir.setEnabled(true);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        boolean v= false;
        if(txtCodigo.getText().isEmpty()||txtCantidad.getText().isEmpty()||txtSucursal.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "No se pueden dejar espacios en blanco");

        }
        else{
            int valor= Integer.parseInt(txtCodigo.getText());
            index=op.encuentraPedido(valor);
            if(index!=-1){
            for(int i=0;i<op.array_Pedido.size();i++){
                Pedido ped = (Pedido)op.array_Pedido.get(i);
                if(op.array_Pedido.get(i).getCodFarmaco()==valor){
                
                    v=true;
                }
            }
            if(v==true){
                int codFarmaco= Integer.parseInt(txtCodigo.getText());
                int cantidad= Integer.parseInt(txtCantidad.getText());
                String sucursal= txtSucursal.getText();
                op.modificar(index, codFarmaco, sucursal, cantidad);
            }
            }
        }
        txtCodigo.setText("");
        txtCantidad.setText("");
        txtSucursal.setText("");
        
        txtCodigo.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtSucursal.setEnabled(false);
        
        
        btnOK.setEnabled(false);
        btnConsultar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnSalir.setEnabled(true);
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
                boolean v = false;
        int cod= Integer.parseInt(txtCodigo.getText());
        if(txtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite un numero de farmaco");
        }
        else{
            for(int i=0; i<op.array_Pedido.size(); i++){
                
                if(op.array_Pedido.get(i).getCodFarmaco()== cod){
                    v= true;
                }
                
            }
        
        
        if(v==true){
            for(int i=0;i<op.array_Pedido.size();i++){
                if(op.array_Pedido.get(i).getCodFarmaco()==cod){
                    op.array_Pedido.remove(i);
                    
                    JOptionPane.showMessageDialog(null, "Se eliminaron correctamente los datos");
                }
                
        
            }
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No se encontro el cliente");
        }
        }
        txtCodigo.setText("");
        txtCantidad.setText("");
        txtSucursal.setText("");
        
        txtCodigo.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtSucursal.setEnabled(false);
        
        
        btnOK.setEnabled(false);
        btnConsultar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnSalir.setEnabled(true);
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtSucursal;
    // End of variables declaration//GEN-END:variables
}
