/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

/**
 *
 * @author E7240
 */
import javax.swing.table.DefaultTableModel;
import Clases.Cliente;
import Clases.Operaciones;
import static Clases.Operaciones.array_Cliente;
import Clases.Facturacion;
import javax.swing.JOptionPane;
public class frmReportes extends javax.swing.JFrame {

    /**
     * Creates new form frmReportes
     */
    DefaultTableModel modelo;
    Operaciones op = new Operaciones();
    public frmReportes() {
        initComponents();
        lblFactura.setVisible(false);
        lblCliente.setVisible(false);
        lblFarmaco.setVisible(false);
        lblDepartamento.setVisible(false);
        lblEstado.setVisible(false);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtReporte = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        cbxReporte = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        lblFarmaco = new javax.swing.JLabel();
        lblDepartamento = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblFactura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Seleccionar un reporte:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtReporte.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtReporte.setName("txtReporte"); // NOI18N
        getContentPane().add(txtReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 190, 30));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.setName("tabla"); // NOI18N
        jScrollPane2.setViewportView(tabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 590, 200));

        cbxReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Cliente", "Farmaco", "Departamento", "Bodega", "Factura" }));
        cbxReporte.setName("cbxReporte"); // NOI18N
        cbxReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxReporteActionPerformed(evt);
            }
        });
        getContentPane().add(cbxReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("REPORTES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        lblCliente.setText("* Digite el genero");
        lblCliente.setName("lblCliente"); // NOI18N
        getContentPane().add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/door_in.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setName("btnSalir"); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        btnOK.setText("OK");
        btnOK.setName("btnOK"); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        lblFarmaco.setText("* Digite el nombre del farmaco");
        lblFarmaco.setName("lblFarmaco"); // NOI18N
        getContentPane().add(lblFarmaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        lblDepartamento.setText("* Digite el nombre del departamento");
        lblDepartamento.setName("lblDepartamento"); // NOI18N
        getContentPane().add(lblDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        lblEstado.setText("* Digite el nombre de la sucursal");
        lblEstado.setName("lblEstado"); // NOI18N
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        lblFactura.setText("* Digite un numero de factura");
        lblFactura.setName("lblFactura"); // NOI18N
        getContentPane().add(lblFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxReporteActionPerformed
        if(cbxReporte.getSelectedIndex()==1){
            
            modelo= new DefaultTableModel();
            
            modelo.addColumn("Nombre");
            modelo.addColumn("Cedula");
            modelo.addColumn("Edad");
            modelo.addColumn("Telefono");
            modelo.addColumn("Correo");
            
            this.tabla.setModel(modelo);
            lblCliente.setVisible(true);
            lblFarmaco.setVisible(false);
            lblDepartamento.setVisible(false);
            lblEstado.setVisible(false); 
            lblFactura.setVisible(false);

        }
        if(cbxReporte.getSelectedIndex()==2){
            modelo = new DefaultTableModel();
            modelo.addColumn("Codigo");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Categoria");
            modelo.addColumn("Cantidad");
            modelo.addColumn("Precio");
            
            this.tabla.setModel(modelo);
            lblFarmaco.setVisible(true);
            lblCliente.setVisible(false);
            lblDepartamento.setVisible(false);
            lblEstado.setVisible(false);
            lblFactura.setVisible(false);

        }
        if(cbxReporte.getSelectedIndex()==3){
            modelo = new DefaultTableModel();
            
            modelo.addColumn("Empleado");
            modelo.addColumn("Codigo");
            this.tabla.setModel(modelo);
            
            lblDepartamento.setVisible(true);
            lblFarmaco.setVisible(false);
            lblCliente.setVisible(false);
            lblEstado.setVisible(false);
            lblFactura.setVisible(false);

        
            
        }
        if(cbxReporte.getSelectedIndex()==4){
             modelo = new DefaultTableModel();
            
            
            modelo.addColumn("Codigo");
            modelo.addColumn("Cantidad");
            modelo.addColumn("Estado");
            this.tabla.setModel(modelo);
            
            lblDepartamento.setVisible(false);
            lblFarmaco.setVisible(false);
            lblCliente.setVisible(false);
            lblEstado.setVisible(true);
            lblFactura.setVisible(false);

        }
        if(cbxReporte.getSelectedIndex()==5){
            modelo = new DefaultTableModel();
            modelo.addColumn("Fecha");
            modelo.addColumn("ID Cliente");
            modelo.addColumn("Cod empleado");
            modelo.addColumn("Cantidad");
            modelo.addColumn("Cod farmaco");
            modelo.addColumn("Precio");
            modelo.addColumn("Total");

            
            this.tabla.setModel(modelo);
            lblFarmaco.setVisible(false);
            lblCliente.setVisible(false);
            lblDepartamento.setVisible(false);
            lblEstado.setVisible(false);
            lblFactura.setVisible(true);
        }
    }//GEN-LAST:event_cbxReporteActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
         
       String[] agregarFilas = new String [9];
       
       String repor= String.valueOf(txtReporte.getText());
        
        
        if(cbxReporte.getSelectedIndex() == 1){

             for(int i =0;i<op.array_Cliente.size();i++ ){
             
                if(repor.equals(op.array_Cliente.get(i).getGenero())){
       
                  agregarFilas[0] = op.array_Cliente.get(i).getNombreCliente();
                  agregarFilas[1] =  String.valueOf(op.array_Cliente.get(i).getCedCliente());
                  agregarFilas[2]= String.valueOf(op.array_Cliente.get(i).getEdad());
                  agregarFilas[3]= String.valueOf(op.array_Cliente.get(i).getTelefono());
                  agregarFilas[4]= op.array_Cliente.get(i).getCorreo();
                   
                  modelo.addRow(agregarFilas);
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se encontro cliente");
                }
            
            }
                         
        }           
            
        
        
         if(cbxReporte.getSelectedIndex() == 2){

             for(int i =0;i<op.array_Farmaco.size();i++ ){
             
                if(repor.equals(op.array_Farmaco.get(i).getNomFarmaco())){
       
                  agregarFilas[0] = String.valueOf(op.array_Farmaco.get(i).getcodFarmaco());
                  agregarFilas[1] =  String.valueOf(op.array_Farmaco.get(i).getDescripcion());
                  agregarFilas[2]= String.valueOf(op.array_Farmaco.get(i).getCategoria());
                  agregarFilas[3]= String.valueOf(op.array_Farmaco.get(i).getCantidad());
                  agregarFilas[4]= String.valueOf(op.array_Farmaco.get(i).getPrecio());
                   
                  modelo.addRow(agregarFilas);
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se encontro farmaco");
                }
            
            }
                         
        }           
            
        
        
        if(cbxReporte.getSelectedIndex() == 3){

             
             for(int j=0;j<op.array_Empleado.size();j++){
                 if(repor.equals(op.array_Empleado.get(j).getDepartamento())){
                     agregarFilas[0]= String.valueOf(op.array_Empleado.get(j).getNombre());
                     agregarFilas[1] =  String.valueOf(op.array_Empleado.get(j).getCodEmpleado());
                     
                     modelo.addRow(agregarFilas);
                 }
                 else{
                    JOptionPane.showMessageDialog(null, "No se encontraron empleados");
                }
             }
                         
        }           
            
               
         if(cbxReporte.getSelectedIndex() == 4){

             
             for(int j=0;j<op.array_Bodega.size();j++){
                 if(repor.equals(op.array_Bodega.get(j).getSucursal())){
                     agregarFilas[0]= String.valueOf(op.array_Bodega.get(j).getCodFarmaco());
                     agregarFilas[1] =  String.valueOf(op.array_Bodega.get(j).getCantidad());
                     agregarFilas[2] =  String.valueOf(op.array_Bodega.get(j).getCodEstado());
                     
                     modelo.addRow(agregarFilas);
                 }
                 else{
                    JOptionPane.showMessageDialog(null, "No se encontro existencias");
                }
             }
                         
        }
         if(cbxReporte.getSelectedIndex() == 5){

             for(int i =0;i<op.array_Factura.size();i++ ){
                 Facturacion fac = (Facturacion)op.array_Factura.get(i);
                 int num= op.array_Factura.get(i).getNumero();
                 int re= Integer.parseInt(txtReporte.getText());
               if(re==num){
                  agregarFilas[0] = String.valueOf(op.array_Factura.get(i).getFecha());
                  agregarFilas[1] =  String.valueOf(op.array_Factura.get(i).getCedCliente());
                  agregarFilas[2]= String.valueOf(op.array_Factura.get(i).getCodEmpleado());
                  agregarFilas[3]= String.valueOf(op.array_Factura.get(i).getCantidad());
                  agregarFilas[4]= String.valueOf(op.array_Factura.get(i).getCodFarmaco());
                  agregarFilas[5]= String.valueOf(op.array_Factura.get(i).getPrecio());
                  agregarFilas[6]= String.valueOf(op.array_Factura.get(i).getTotalFinal());
                   
                  modelo.addRow(agregarFilas);
                   
               }
       
                  }
            
              
                   
            
        txtReporte.setText("");
                                         
         }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFactura;
    private javax.swing.JLabel lblFarmaco;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtReporte;
    // End of variables declaration//GEN-END:variables
}
